[package]
name = "atb-graphql-ext"
description.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
atb-graphql-derive = { path = "./derive" }
async-graphql = { version = "7" }
